### ISSUE TITLE
Generalizing on first name

### ISSUE THREAD

**Issue by v5out** [RasaHQ/financial-demo#55]
I'm new to Rasa and using this demo to learn. When I run it, I can type in "pay Karen" or "pay Lisa" and it works fine but if I say "pay Percy" it says "Sorry, I didn't get that." Percy is in the list of known recipients.

Why doesn't it work with Percy?

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @tabergma will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by melindaloubser1** [comment]
Hi @v5out - I noticed this also, it seems that the spacy entity extractor is better at picking up some names than others. So, it's not that Percy isn't recognized as being on the list, it's just that the name isn't extracted in the first place, depending on the sentence context. A recent PR changed the names to ones that seemed well-recognized, but if that still isn't the case, feel free to open a PR to change the names to ones that are well recognized.

**Comment by melindaloubser1** [comment]
https://github.com/RasaHQ/financial-demo/pull/54

**Comment by v5out** [comment]
@melindaloubser1 Thanks for the clarification. What's the best way to improve the named entity recognition for this demo? Does Spacy need to be fine-tuned or trained in some way?

**Comment by melindaloubser1** [comment]
Spacy is a pretrained extractor, so there's no fine-tuning that inside the pipeline. In general, one option is to secondarily fill the slot `from_text` and then validate it, so that if spacy doesn't pick up a free-standing name the raw text input is taken. It's also possible to add a custom entity like `name`, and use that in conjunction with spacy, but that is not going to generalize well. It would make most sense if there was a known and limited set of names; for a real-world application, that's almost never  the case.

Part of why PR 54 added surnames is that spacy is much better at recognizing `Firstname Surname` patterns than just `Firstname`. So, maybe it would be best to just add a hint in the prompt - "What is the full name of the person you want to pay?"

**Comment by v5out** [comment]
Thanks! Closing this issue.
